name: Publish Container Image
on: [push]
jobs:
publish-docker-image:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Login to GitHub Container Registry
uses: docker/login-action@v1
with:
registry: ghcr.io
username: ${{ github.actor }}
password: ${{ secrets.GITHUB_TOKEN }}
- name: Build & Push Container Image
run: |
       docker build . --tag ghcr.io/alexanderbazo/flutter-sdk-image-with-fastlane:latest
       docker run ghcr.io/alexanderbazo/flutter-sdk-image-with-fastlane:latest
       docker push ghcr.io/alexanderbazo/flutter-sdk-image-with-fastlane:latest
